Task 01 - setup
MastersAcademy/fe-react-2024 pull request #22
Opened 2024-04-20 10:08 UTC by Bogdandrummer

-  Mentor is added to pr
- AC copied to pr description
- link to deployed version added to pr
- About block (text and image) added to main page
- On the widths 390px and 1280px, the site layout corresponds to the design

Link to deployed page:
https://bogdandrummer.github.io/fe-react-2024/

2024-04-20 11:43 UTC, MZabolotnev commented
Mobile view does not match design. Pls check font size, photo should be from above, and with paddings. Also no padding before profile link. 
<img width="382" alt="image" src="https://github.com/MastersAcademy/fe-react-2024/assets/25617217/3e1da356-73a6-4813-b181-cfce584c94fe">
<img width="423" alt="image" src="https://github.com/MastersAcademy/fe-react-2024/assets/25617217/b3178ab8-0f62-4421-939d-9446ca7c14c1">

2024-04-20 11:43 UTC, MZabolotnev requested changes

2024-04-20 11:43 UTC, MZabolotnev commented on src/components/about/About.tsx
> +                    <div className="about__block">
It can be more semantic. Use article and section tags instead div.

2024-04-20 11:43 UTC, MZabolotnev commented on src/components/about/About.tsx
> +                                </a>{' '}
{' '} - Is it necessary here?

2024-04-20 11:43 UTC, MZabolotnev commented on src/reset.css
> +/*Обнуление*/
Please use English

2024-04-20 11:43 UTC, MZabolotnev commented on src/reset.css
> +/*}*/
Pls remove commented code

2024-04-23 10:34 UTC, vladyslav-yermolin-moc commented
Hey, @Bogdandrummer, you have created pr to our main repo - https://github.com/MastersAcademy/fe-react-2024. 

But according to our flow, you should create pr to your repo - https://github.com/Bogdandrummer/fe-react-2024/tree/main

So I close this pr

2024-04-23 10:34 UTC, closed without merging